AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation Template for Roman Numerals Converter Application. 
  This template creates Python Flask Web Application on Amazon Linux 2023  
  EC2 Instance with custom security group allowing http connections on port 80 and SSH connection on port 22. 
  Roman Numerals Converter Application is downloaded from Github repository, then installed on Flask.
  
Parameters:
  Samokeypair:
    Description: Enter your keyname
    Type: AWS::EC2::KeyPair::KeyName
  LatestAMIId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64'
  
Resources:

  ConverterSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "String" # Required
      SecurityGroupIngress: 
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80

  ConverterHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAMIId
      InstanceType: t2.micro
      KeyName: !Ref Samokeypair
      SecurityGroups: 
        - !Ref ConverterSecGrp
      Tags: 
        - Key: Name
          Value: web server of ${AWS::StackName}
      UserData: !Base64 
        #! /bin/bash
        dnf update -y
        dnf install python3 -y
        dnf install python3-pip -y
        pip3 install flask
        dnf install git -y
        FOLDER= "https://github.com/harputsamed/AWS_Projects/tree/main/001-roman-numerals-converter/templates"
        wget -P templates ${FOLDER}/index.html
        wget -P templates ${FOLDER}/result.html
        wget https://raw.githubusercontent.com/harputsamed/AWS_Projects/refs/heads/main/001-roman-numerals-converter/roman-numerals-converter-app.py
        python3 roman-numerals-converter-app.py 

Outputs:
  WebsiteURL:
    Value: !Sub 
      - http://${UrlName}
      - UrlName: !GetAtt ConverterHost.PublicDnsName